changes made for cvp-1871
redhat-openshift-ecosystem/operator-test-playbooks pull request #157
Opened 2021-06-21 14:58 UTC by LikhithaEda

**CVP-1871**
The changes I made are getting rid of ansible-lint warnings & errors. 
I resolved errors such as : 
   - too many spaces before colon  (colons)
   - too few spaces before comment  (comments)
   - line too long (98 > 80 characters)

2021-06-21 15:17 UTC, samvarankashyap commented on ansible-lint.yml
> +  - '602'
@LikhithaEda Why is 602 added. 
which rule is it.

2021-06-21 15:20 UTC, 14rcole approved these changes
LGTM nice work

2021-06-21 15:46 UTC, samvarankashyap commented
@LikhithaEda 
Please change the title of the PR to following format

CVP-1871 <title of the ticket >

2021-06-21 19:10 UTC, LikhithaEda reviewed
> @LikhithaEda
> Please change the title of the PR to following format
> 
> CVP-1871 <title of the ticket >

done

2021-06-22 14:29 UTC, lslebodn commented
@LikhithaEda  Please rebase on top of current master

2021-06-22 14:30 UTC, lslebodn commented
BTW @mvalarh introduced some config file as well as part of his change
https://github.com/redhat-operator-ecosystem/operator-test-playbooks/blob/master/.ansible-lint

It would be good to use just a one file

2021-06-23 06:12 UTC, mvalarh approved these changes

2021-06-23 09:43 UTC, lslebodn requested changes
https://github.com/redhat-operator-ecosystem/operator-test-playbooks/pull/157/checks?check_run_id=2892725111

The check  "Run ansible-lint and yamllint for this repo. / build" still do not pass

-1

2021-06-24 11:46 UTC, lslebodn commented
@LikhithaEda  Could you explain why new file local.yml was added in the pull request.
We were supposed to fix linting issues. I cannot see a relation with adding new files.

Moreover, I can still se two configuration for ansible lint in different files.
* https://github.com/LikhithaEda/operator-test-playbooks/blob/local/.ansible-lint
* https://github.com/LikhithaEda/operator-test-playbooks/blob/local/ansible-lint.yml

We should use just one configuration.

2021-06-25 10:11 UTC, lslebodn requested changes
Some of question still has not been answered ^^

2021-06-25 21:56 UTC, LikhithaEda reviewed
> https://github.com/redhat-operator-ecosystem/operator-test-playbooks/pull/157/checks?check_run_id=2892725111
> 
> The check "Run ansible-lint and yamllint for this repo. / build" still do not pass
> 
> -1

I solved this issue in the new commit

2021-06-25 21:59 UTC, LikhithaEda commented
> @LikhithaEda Could you explain why new file local.yml was added in the pull request.
> We were supposed to fix linting issues. I cannot see a relation with adding new files.
> 
> Moreover, I can still se two configuration for ansible lint in different files.
> 
>     * https://github.com/LikhithaEda/operator-test-playbooks/blob/local/.ansible-lint
> 
>     * https://github.com/LikhithaEda/operator-test-playbooks/blob/local/ansible-lint.yml
> 
> 
> We should use just one configuration.

I did not add the local.yml file. It was already there and just modified to fix linting errors. I think after the rebase it is showing as a new file. And the reason the check failed previously is because of a syntax error in the local.yml which I fixed this time.

2021-06-25 22:14 UTC, LikhithaEda commented
> BTW @mvalarh introduced some config file as well as part of his change
> https://github.com/redhat-operator-ecosystem/operator-test-playbooks/blob/master/.ansible-lint
> 
> It would be good to use just a one file
I rebased after this changes were merged but I don't see this file locally for some reason. Should I add it myself?

2021-06-28 13:40 UTC, lslebodn commented
> @lslebodn I did not add the local.yml file. It was already there and just modified to fix linting errors. I think after the rebase it is showing as a new file. And the reason the check failed previously is because of a syntax error in the local.yml which I fixed this time.

Github says you added the file.
* https://patch-diff.githubusercontent.com/raw/redhat-operator-ecosystem/operator-test-playbooks/pull/157.patch
```
diff --git a/local.yml b/local.yml
new file mode 100644
index 00000000..f93dc3cf
--- /dev/null
+++ b/local.yml
@@ -0,0 +1,112 @@
+---
+- name: Test
```

2021-06-28 13:40 UTC, lslebodn commented
@samvarankashyap  please help @LikhithaEda  with rebase

2021-06-29 08:36 UTC, lslebodn requested changes
The story says:
```
Remove as much rules from the ansible-lint.yml skip_list as possible
```
and there are also list of rules which should be removed from the configuration file.
But we did not change anything in configuration.
There is just new-line added.

Fixing linting violation is nice but we need to ensure nobody else will introduce them in the future. Which is not done in current MR.

We should also remove duplicate configuration for ansible lint
* https://github.com/LikhithaEda/operator-test-playbooks/blob/local/.ansible-lint
* https://github.com/LikhithaEda/operator-test-playbooks/blob/local/ansible-lint.yml

There is not any reason to have two different files for the same purpose.

2021-06-29 14:55 UTC, LikhithaEda commented
> The story says:
> 
> ```
> Remove as much rules from the ansible-lint.yml skip_list as possible
> ```
> 
> and there are also list of rules which should be removed from the configuration file.
> But we did not change anything in configuration.
> There is just new-line added.
> 
> Fixing linting violation is nice but we need to ensure nobody else will introduce them in the future. Which is not done in current MR.
> 
> We should also remove duplicate configuration for ansible lint
> 
>     * https://github.com/LikhithaEda/operator-test-playbooks/blob/local/.ansible-lint
> 
>     * https://github.com/LikhithaEda/operator-test-playbooks/blob/local/ansible-lint.yml
> 
> 
> There is not any reason to have two different files for the same purpose.

The two files: **.ansible-lint** and **ansible-lint.yml** have different contents.

2021-07-07 20:35 UTC, wheelerlaw commented
@LikhithaEda and I merged the `.ansible-lint` and `ansible-lint.yml` file into a single `.ansible-lint` file.

2021-07-08 10:59 UTC, dirgim commented
/retest

2021-07-08 14:04 UTC, wheelerlaw commented
> /retest

Lihkitha will need to rebase on top of the current master in order for the checks to pass.

2021-07-09 15:04 UTC, 14rcole commented on .ansible-lint
> +  - '102'
Can you add comments to these lines saying what each of the errors is

2021-07-09 16:59 UTC, 14rcole commented
LGTM

2021-07-09 17:05 UTC, wheelerlaw commented
lgtm. let's get this merged in for now and we can make more changes in the future.

2021-07-09 17:05 UTC, wheelerlaw approved these changes

2021-07-09 18:05 UTC, merged

2021-07-12 17:09 UTC, lslebodn commented
/test CVP